Adding support for a JSON inventory.

diff --git a/.github/workflows/NightlyRelease.yml b/.github/workflows/NightlyRelease.yml
--- a/.github/workflows/NightlyRelease.yml
+++ b/.github/workflows/NightlyRelease.yml
@@ -68,6 +68,14 @@ on:
         description: 'Multi-line string containing artifact:file:title asset descriptions.'
         required: true
         type: string
+      inventory-json:
+        type: string
+        required: false
+        default: ''
+      inventory-version:
+        type: string
+        required: false
+        default: ''
       tarball-name:
         type: string
         required: false
@@ -185,6 +193,7 @@ jobs:
           ANSI_LIGHT_RED=$'\x1b[91m'
           ANSI_LIGHT_GREEN=$'\x1b[92m'
           ANSI_LIGHT_YELLOW=$'\x1b[93m'
+          ANSI_LIGHT_BLUE="\e[94m"
           ANSI_NOCOLOR=$'\x1b[0m'
 
           export GH_TOKEN=${{ github.token }}
@@ -202,6 +211,30 @@ jobs:
             printf "%s\n" "$line"
           }
 
+          # Create JSON inventory
+          if [[ "${{ inputs.inventory-json }}" != "" ]]; then
+            VERSION="1.0"
+            ORDER=("os-name" "os-version" "os-arch" "runtime" "ghdl-backend")
+
+            jsonInventory=$(jq -c -n \
+              --arg version "${VERSION}" \
+              --arg date "$(date +"%Y-%m-%dT%H-%M-%S%:z")" \
+              --argjson jsonMeta "$(jq -c -n \
+                --arg tag "${{ inputs.nightly_name }}" \
+                --arg version "${{ inputs.inventory-version }}" \
+                --arg hash "${{ github.sha }}" \
+                --arg repo "${{ github.server_url }}/${{ github.repository }}" \
+                '{"tag": $tag, "version": $version, "git-hash": $hash, "repository-url": $repo}' \
+              )" \
+              --argjson jsonInfo "$(jq -c -n \
+                --arg url "${{ github.server_url }}/${{ github.repository }}/releases/download/${{ inputs.nightly_name }}" \
+                --argjson order "$(jq -c -n '$ARGS.positional' --args "${ORDER[@]}")" \
+                '{"release-url": $url, "categories": $order}'
+              )" \
+              '{"version": 1.0, "timestamp": $date, "meta": $jsonMeta, "info": $jsonInfo, "files": {}}'
+            )
+          fi
+
           ERRORS=0
           # A dictionary of 0/1 to avoid duplicate downloads
           declare -A downloadedArtifacts
@@ -214,12 +247,20 @@ jobs:
 
             # split assetLine colon separated triple: artifact:asset:title
             artifact="${assetLine%%:*}"
-            remaining="${assetLine#*:}"
-            asset="${remaining%%:*}"
-            title="${remaining##*:}"
+            assetLine="${assetLine#*:}"
+            asset="${assetLine%%:*}"
+            assetLine="${assetLine#*:}"
+            if [[ "${{ inputs.inventory-json }}" == "" ]]; then
+              categories=""
+              title="${assetLine##*:}"
+            else
+              categories="${assetLine%%:*}"
+              title="${assetLine##*:}"
+            fi
 
             # remove leading whitespace
             asset="${asset#"${asset%%[![:space:]]*}"}"
+            categories="${categories#"${categories%%[![:space:]]*}"}"
             title="${title#"${title%%[![:space:]]*}"}"
 
             # apply replacements
@@ -227,7 +268,7 @@ jobs:
             title="$(Replace "${title}")"
 
             printf "%s\n" "Publish asset '${asset}' from artifact '${artifact}' with title '${title}'"
-            printf "%s" "  Checked asset for duplicates ... "
+            printf "  %s" "Checked asset for duplicates ... "
             if [[ -n "${assetFilenames[$asset]}" ]]; then
               printf "%s\n" "${ANSI_LIGHT_RED}[ERROR]${ANSI_NOCOLOR}"
               printf "%s\n" "::error title=DuplicateAsset::Asset '${asset}' from artifact '${artifact}' was already uploaded to release '${{ inputs.nightly_name }}'."
@@ -240,10 +281,10 @@ jobs:
 
             # Download artifact by artifact name
             if [[ -n "${downloadedArtifacts[$artifact]}" ]]; then
-              printf "%s\n" "  downloading '${artifact}' ... ${ANSI_LIGHT_YELLOW}[SKIPPED]${ANSI_NOCOLOR}"
+              printf "  %s\n" "downloading '${artifact}' ... ${ANSI_LIGHT_YELLOW}[SKIPPED]${ANSI_NOCOLOR}"
             else
               echo    "  downloading '${artifact}' ... "
-              printf "%s" "    gh run download $GITHUB_RUN_ID --dir \"${artifact}\" --name \"${artifact}\" "
+              printf "    %s" "gh run download $GITHUB_RUN_ID --dir \"${artifact}\" --name \"${artifact}\" "
               gh run download $GITHUB_RUN_ID --dir "${artifact}" --name "${artifact}"
               if [[ $? -eq 0 ]]; then
                 printf "%s\n" "${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}"
@@ -256,13 +297,13 @@ jobs:
               fi
               downloadedArtifacts[$artifact]=1
 
-              printf "%s" "  Checking for embedded tarball ... "
+              printf "  %s" "Checking for embedded tarball ... "
               if [[ -f "${artifact}/${{ inputs.tarball-name }}" ]]; then
                 printf "%s\n" "${ANSI_LIGHT_GREEN}[FOUND]${ANSI_NOCOLOR}"
 
                 pushd "${artifact}" > /dev/null
 
-                printf "%s" "    Extracting embedded tarball ... "
+                printf "    %s" "Extracting embedded tarball ... "
                 tar -xf "${{ inputs.tarball-name }}"
                 if [[ $? -ne 0 ]]; then
                   printf "%s\n" "${ANSI_LIGHT_RED}[FAILED]${ANSI_NOCOLOR}"
@@ -270,7 +311,7 @@ jobs:
                   printf "%s\n" "${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}"
                 fi
 
-                printf "%s" "    Removing temporary tarball ... "
+                printf "    %s" "Removing temporary tarball ... "
                 rm -f "${{ inputs.tarball-name }}"
                 if [[ $? -ne 0 ]]; then
                   printf "%s\n" "${ANSI_LIGHT_RED}[FAILED]${ANSI_NOCOLOR}"
@@ -285,20 +326,20 @@ jobs:
             fi
 
             # Check if artifact should be compressed (zip, tgz) or if asset was part of the downloaded artifact.
-            printf "%s" "  checking asset '${artifact}/${asset}' ... "
+            printf "  %s" "checking asset '${artifact}/${asset}' ... "
             if [[ "${asset}" == !*.zip ]]; then
               printf "%s\n" "${ANSI_LIGHT_GREEN}[ZIP]${ANSI_NOCOLOR}"
               asset="${asset##*!}"
-              printf "%s\n" "    Compressing artifact '${artifact}' to '${asset}' ..."
+              printf "    %s\n" "Compressing artifact '${artifact}' to '${asset}' ..."
               (
                 cd "${artifact}" && \
                 zip -r "../${asset}" *
               )
               if [[ $? -eq 0 ]]; then
-                printf "%s\n" "    Compression ${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}"
+                printf "    %s\n" "Compression ${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}"
                 uploadFile="${asset}"
               else
-                printf "%s\n" "    Compression ${ANSI_LIGHT_RED}[ERROR]${ANSI_NOCOLOR}"
+                printf "    %s\n" "Compression ${ANSI_LIGHT_RED}[ERROR]${ANSI_NOCOLOR}"
                 printf "%s\n" "${ANSI_LIGHT_RED}Couldn't compress '${artifact}' to zip file '${asset}'.${ANSI_NOCOLOR}"
                 printf "%s\n" "::error title=CompressionError::Couldn't compress '${artifact}' to zip file '${asset}'."
                 ERRORS=1
@@ -310,12 +351,12 @@ jobs:
               if [[ "${asset:0:1}" == "\$" ]]; then
                 asset="${asset##*$}"
                 dirName="${asset%.*}"
-                printf "%s\n" "    Compressing artifact '${artifact}' to '${asset}' ..."
+                printf "    %s\n" "Compressing artifact '${artifact}' to '${asset}' ..."
                 tar -c --gzip --owner=0 --group=0 --file="${asset}" --directory="${artifact}" --transform "s|^\.|${dirName%.tar}|" .
                 retCode=$?
               else
                 asset="${asset##*!}"
-                printf "%s\n" "    Compressing artifact '${artifact}' to '${asset}' ..."
+                printf "    %s\n" "Compressing artifact '${artifact}' to '${asset}' ..."
                 (
                   cd "${artifact}" && \
                   tar -c --gzip --owner=0 --group=0 --file="../${asset}" *
@@ -324,10 +365,10 @@ jobs:
               fi
 
               if [[ $retCode -eq 0 ]]; then
-                printf "%s\n" "    Compression ${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}"
+                printf "    %s\n" "Compression ${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}"
                 uploadFile="${asset}"
               else
-                printf "%s\n" "    Compression ${ANSI_LIGHT_RED}[ERROR]${ANSI_NOCOLOR}"
+                printf "    %s\n" "Compression ${ANSI_LIGHT_RED}[ERROR]${ANSI_NOCOLOR}"
                 printf "%s\n" "${ANSI_LIGHT_RED}Couldn't compress '${artifact}' to tgz file '${asset}'.${ANSI_NOCOLOR}"
                 printf "%s\n" "::error title=CompressionError::Couldn't compress '${artifact}' to tgz file '${asset}'."
                 ERRORS=1
@@ -339,12 +380,12 @@ jobs:
               if [[ "${asset:0:1}" == "\$" ]]; then
                 asset="${asset##*$}"
                 dirName="${asset%.*}"
-                printf "%s\n" "    Compressing artifact '${artifact}' to '${asset}' ..."
+                printf "    %s\n" "Compressing artifact '${artifact}' to '${asset}' ..."
                 tar -c --zstd --owner=0 --group=0 --file="${asset}" --directory="${artifact}" --transform "s|^\.|${dirName%.tar}|" .
                 retCode=$?
               else
                 asset="${asset##*!}"
-                printf "%s\n" "    Compressing artifact '${artifact}' to '${asset}' ..."
+                printf "    %s\n" "Compressing artifact '${artifact}' to '${asset}' ..."
                 (
                   cd "${artifact}" && \
                   tar -c --zstd --owner=0 --group=0 --file="../${asset}" *
@@ -353,10 +394,10 @@ jobs:
               fi
 
               if [[ $retCode -eq 0 ]]; then
-                printf "%s\n" "    Compression ${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}"
+                printf "    %s\n" "Compression ${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}"
                 uploadFile="${asset}"
               else
-                printf "%s\n" "    Compression ${ANSI_LIGHT_RED}[ERROR]${ANSI_NOCOLOR}"
+                printf "    %s\n" "Compression ${ANSI_LIGHT_RED}[ERROR]${ANSI_NOCOLOR}"
                 printf "%s\n" "${ANSI_LIGHT_RED}Couldn't compress '${artifact}' to zst file '${asset}'.${ANSI_NOCOLOR}"
                 printf "%s\n" "::error title=CompressionError::Couldn't compress '${artifact}' to zst file '${asset}'."
                 ERRORS=1
@@ -373,8 +414,35 @@ jobs:
               continue
             fi
 
+            # Add asset to JSON inventory
+            if [[ "${{ inputs.inventory-json }}" != "" ]]; then
+              if [[ "${categories}" != "${title}" ]]; then
+                printf "  %s\n" "adding file '${uploadFile}' with '${categories//;/ → }' to JSON inventory ..."
+                category=""
+                jsonEntry=$(jq -c -n \
+                  --arg title "${title}" \
+                  --arg file "${uploadFile}" \
+                  '{"file": $file, "title": $title}' \
+                )
+
+                while [[ "${categories}" != "${category}" ]]; do
+                  category="${categories##*;}"
+                  categories="${categories%;*}"
+                  jsonEntry=$(jq -c -n --arg cat "${category}" --argjson value "${jsonEntry}" '{$cat: $value}')
+                done
+
+                jsonInventory=$(jq -c -n \
+                  --argjson inventory "${jsonInventory}" \
+                  --argjson file "${jsonEntry}" \
+                  '$inventory * {"files": $file}' \
+                )
+              else
+                printf "  %s\n" "adding file '${uploadFile}' to JSON inventory ... ${ANSI_LIGHT_YELLOW}[SKIPPED]${ANSI_NOCOLOR}"
+              fi
+            fi
+
             # Upload asset to existing release page
-            printf "%s" "  uploading asset '${asset}' from '${uploadFile}' with title '${title}' ... "
+            printf "  %s" "uploading asset '${asset}' from '${uploadFile}' with title '${title}' ... "
             gh release upload ${{ inputs.nightly_name }} "${uploadFile}#${title}" --clobber
             if [[ $? -eq 0 ]]; then
               printf "%s\n" "${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}"
@@ -387,8 +455,32 @@ jobs:
             fi
           done <<<'${{ inputs.assets }}'
 
-          printf "%s\n" "Inspecting downloaded artifacts ..."
+          if [[ "${{ inputs.inventory-json }}" != "" ]]; then
+            inventoryTitle="Release Inventory (JSON)"
+
+            printf "%s\n" "Publish asset '${{ inputs.inventory-json }}' with title '${inventoryTitle}'"
+            printf "::group::${ANSI_LIGHT_BLUE}%s${ANSI_NOCOLOR}\n" "Writing JSON inventory to '${{ inputs.inventory-json }}' ...."
+            printf "%s\n" "$(jq -n --argjson inventory "${jsonInventory}" '$inventory')" > "${{ inputs.inventory-json }}"
+            cat "${{ inputs.inventory-json }}"
+            printf "::endgroup::\n"
+
+            # Upload inventory asset to existing release page
+            printf "  %s" "uploading asset '${{ inputs.inventory-json }}' title '${inventoryTitle}' ... "
+            gh release upload ${{ inputs.nightly_name }} "${{ inputs.inventory-json }}#${inventoryTitle}" --clobber
+            if [[ $? -eq 0 ]]; then
+              printf "%s\n" "${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}"
+            else
+              printf "%s\n" "${ANSI_LIGHT_RED}[ERROR]${ANSI_NOCOLOR}"
+              printf "%s\n" "${ANSI_LIGHT_RED}Couldn't upload asset '${{ inputs.inventory-json }}' to release '${{ inputs.nightly_name }}'.${ANSI_NOCOLOR}"
+              printf "%s\n" "::error title=UploadError::Couldn't upload asset '${{ inputs.inventory-json }}' to release '${{ inputs.nightly_name }}'."
+              ERRORS=1
+              continue
+            fi
+          fi
+
+          printf "::group::${ANSI_LIGHT_BLUE}%s${ANSI_NOCOLOR}\n" "Inspecting downloaded artifacts ..."
           tree -pash -L 3 .
+          printf "::endgroup::\n"
 
           if [[ $ERROR -ne 0 ]]; then
             printf "%s\n" "${ANSI_LIGHT_RED}Errors detected in previous steps.${ANSI_NOCOLOR}"
