Workaround 2 - % sign in a filename.

diff --git a/.github/workflows/SphinxDocumentation.yml b/.github/workflows/SphinxDocumentation.yml
--- a/.github/workflows/SphinxDocumentation.yml
+++ b/.github/workflows/SphinxDocumentation.yml
@@ -180,6 +180,39 @@ jobs:
           sphinx-build -v -n -b latex -d _build/doctrees -j $(nproc) -w _build/latex.log . _build/latex
 #           --builder html --doctree-dir _build/doctrees --verbose --fresh-env --write-all --nitpicky --warning-file _build/html.log . _build/html
 
+      - name: Workaround II - https://github.com/sphinx-doc/sphinx/issues/13189
+        if: inputs.latex_artifact != ''
+        run: |
+          printf "Changing directory to 'doc/_build/latex' ...\n"
+          cd doc/_build/latex
+
+          printf "Searching for downloaded images, that need normalization ...\n"
+          for imageExt in png svg jpg jpeg; do
+            printf "  Processing '%s' ...\n" "${imageExt}"
+            while IFS=$'\n' read -r imageFile; do
+              newFile="${imageFile//%/_}";
+
+              printf "    %s\n" "$imageFile";
+              if [[ "${imageFile}" != "${newFile}" ]]; then
+                printf "      Rename file to '%s' " "${newFile}"
+                mv "${imageFile}" "${newFile}"
+                if [[ $? -eq 0 ]]; then
+                  printf "[OK]\n"
+                else
+                  printf "[FAILED]\n"
+                fi
+
+                printf "      Patching LaTeX file for '%s' " "${newFile}"
+                sed -i "s:\{\{${imageFile%.*}\}\.${imageFile##*.}\}:{{${newFile%.*}}.${newFile##*.}}:g" *.tex
+                if [[ $? -eq 0 ]]; then
+                  printf "[OK]\n"
+                else
+                  printf "[FAILED]\n"
+                fi
+              fi
+            done <<<$(find . -type f -iname "*.$imageExt" | sed 's:./::')
+          done
+
       - name: 📤 Upload 'LaTeX Documentation' artifact
         if: inputs.latex_artifact != ''
         continue-on-error: true
